import os
from skpy import Skype

author = os.getenv("COMMIT_AUTHOR")

username = os.environ.get("SKYPE_USERNAME")
password = os.environ.get("SKYPE_PASSWORD")
recipient_id = "live:.cid.a47b92b06acd5a39"
group_id = "19:1e55bc9219844d01a3b27253a2f78652@thread.skype"
message = "Hello! from Skype, message automated generated by skype bot and triggered by github action. \n\n" + f"Commit Author: {author}"
try:
    skype = Skype(username, password)
    chat = skype.chats.chat(group_id)
    chat.sendMsg(message)
    print("Message sent successfully!")

except Exception as e:
    print(f"Failed to send message: {e}")
