import os

# Environment variables
author = os.getenv('AUTHOR_NAME')
branch_name = os.getenv('BRANCH_NAME')
release_notes = os.getenv('RELEASE_NOTES')
build_result = os.getenv('BUILD_FAILED')
build_error = os.getenv('BUILD_ERROR')

if build_result == 'failure':
    message = f"""
    🚨 **Deployment Alert!**

    This is an automated message generated by a Skype bot and triggered by a GitHub Action.

    ---

    ❌ **Build Failed**

    👤 **Triggered By:**  
    {author}

    🌿 **Branch Name:**  
    {branch_name}

    ---

    📄 **Error Details:**  
    {build_error}

    ---

    Please address the issue as soon as possible. Thank you! 🙏
    """
else:
    message = f"""
    🚀 **Hello!**

    This is an automated message generated by a Skype bot and triggered by a GitHub Action.

    ---

    👤 **Released By:**  
    {author}

    🌿 **Branch Name:**  
    {branch_name}

    ---

    📝 **Release Notes:**  
    {release_notes}

    ---

    Thank you! 🙏
    """

# Function to send the message through Skype bot
# send_skype_message(message)

print(message)
