name: Run Python Script

on:
    push:
        branches: [master]

env:
    SKYPE_USERNAME: ${{ secrets.SKYPE_USERNAME }}
    SKYPE_PASSWORD: ${{ secrets.SKYPE_PASSWORD }}

jobs:
    run-python-script:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4 # Checkout repository code

            - name: Get Latest Commit Author
              id: commit_info
              run: echo "AUTHOR_NAME=$(git log -n 1 --pretty=format:'%an')" >> $GITHUB_ENV

            - name: Set up Python environment
              uses: actions/setup-python@v5 # Set up Python version
              with:
                  python-version: '3.x' # Specify your desired Python version (e.g., 3.8)

            - name: Install dependencies
              run: |
                  pip install skpy

            - name: Debug - Check AUTHOR_NAME
              run: |
                  echo "AUTHOR_NAME=$AUTHOR_NAME"
              env:
                  AUTHOR_NAME: ${{ env.AUTHOR_NAME }}

            - name: Run Python script
              env:
                  AUTHOR_NAME: ${{ env.AUTHOR_NAME }} # Pass the environment variable to the script
              run: |
                  python notification.py
