name: Run Python Script

on:
    push:
        branches: [master]

env:
    SKYPE_USERNAME: ${{ secrets.SKYPE_USERNAME }}
    SKYPE_PASSWORD: ${{ secrets.SKYPE_PASSWORD }}

jobs:
    run-python-script:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4 # Checkout repository code

            - name: Get Latest Commit Author
              id: commit_info
              run: echo "AUTHOR_NAME=$(git log -n 1 --pretty=format:'%an')" >> $GITHUB_ENV

            - name: Read Release Notes
              id: read_release_notes
              run: |
                  if [ -f "RELEASE_NOTES.md" ]; then
                    echo "RELEASE_NOTES=$(cat RELEASE_NOTES.md)" >> $GITHUB_ENV
                  else
                    echo "RELEASE_NOTES=No release notes found" >> $GITHUB_ENV
                  fi

            - name: Set up Python environment
              uses: actions/setup-python@v5 # Set up Python version
              with:
                  python-version: '3.x' # Specify your desired Python version (e.g., 3.8)

            - name: Install dependencies
              run: |
                  pip install skpy

            - name: Debug - Check Environment Variables
              run: |
                  echo "AUTHOR_NAME=$AUTHOR_NAME"
                  echo "RELEASE_NOTES=$RELEASE_NOTES"
              env:
                  AUTHOR_NAME: ${{ env.AUTHOR_NAME }}
                  RELEASE_NOTES: ${{ env.RELEASE_NOTES }}

            - name: Run Python script
              env:
                  AUTHOR_NAME: ${{ env.AUTHOR_NAME }} # Pass the environment variable to the script
                  RELEASE_NOTES: ${{ env.RELEASE_NOTES }}
              run: |
                  python notification.py
