name: Run Python Script

on:
    push:
        branches: [master]

env:
    SKYPE_USERNAME: ${{ secrets.SKYPE_USERNAME }}
    SKYPE_PASSWORD: ${{ secrets.SKYPE_PASSWORD }}
    AUTHOR_NAME: 'ZAMAN'

jobs:
    commit-info:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Get Latest Commit Author
              run: |
                  git log -n 1 --pretty=format:'%an' > AUTHOR_NAME  # Store author name in env var
                  git log -n 1 --pretty=format:'%an' | xargs -I {} echo "AUTHOR_NAME={}" >> $GITHUB_ENV
                  echo "AUTHOR_NAME='Your desired author name'" >> $GITHUB_ENV

    run-python-script:
        runs-on: ubuntu-latest # Runner operating system
        needs: commit-info
        steps:
            - uses: actions/checkout@v4 # Checkout repository code

            - name: Set up Python environment
              uses: actions/setup-python@v5 # Set up Python version
              with:
                  python-version: '3.x' # Specify your desired Python version (e.g., 3.8)

            - name: Install dependencies
              run: |
                  pip install skpy

            - name: Run Python script
              run: |
                  python notification.py
